SELECT 
    M.ID_MEMBER,
    F.ID_FILM,
    J.ID_THEATER,
    T.HARGA AS HARGA_ASLI,
    T.HARGA * 0.3 AS HARGA_SETELAH_DISKON
FROM MEMBER M
JOIN TRANSAKSI TR ON M.ID_MEMBER = TR.ID_MEMBER
JOIN JADWAL J ON TR.ID_JADWAL = J.ID_JADWAL
JOIN FILM F ON J.ID_FILM = F.ID_FILM
JOIN THEATER T ON J.ID_THEATER = T.ID_THEATER
WHERE 
    F.JUDUL = 'Keluarga Cemara'
    AND TR.TANGGAL >= TO_DATE('2019-12-19','YYYY-MM-DD');