CREATE TABLE TEATERS (
nomor_teater VARCHAR2(20) PRIMARY KEY
);

CREATE TABLE KURSI (
nomor_kursi VARCHAR2(5),
nomor_teater VARCHAR2(20),
CONSTRAINT fk_kursi_teater
FOREIGN KEY (nomor_teater)
REFERENCES TEATERS(nomor_teater)
);

INSERT INTO TEATERS VALUES ('Teater 1');
INSERT INTO TEATERS VALUES ('Teater 2');
INSERT INTO TEATERS VALUES ('Teater 3');
INSERT INTO TEATERS VALUES ('Teater 4');
INSERT INTO TEATERS VALUES ('Teater 5');

SELECT * FROM TEATERS;

INSERT INTO KURSI VALUES ('A1','Teater 1');
INSERT INTO KURSI VALUES ('A2','Teater 1');
INSERT INTO KURSI VALUES ('A3','Teater 1');
INSERT INTO KURSI VALUES ('A4','Teater 1');

INSERT INTO KURSI VALUES ('B1','Teater 2');
INSERT INTO KURSI VALUES ('B2','Teater 2');
INSERT INTO KURSI VALUES ('B3','Teater 2');

INSERT INTO KURSI VALUES ('C1','Teater 3');
INSERT INTO KURSI VALUES ('C2','Teater 3');

INSERT INTO KURSI VALUES ('D1','Teater 4');
INSERT INTO KURSI VALUES ('D2','Teater 4');

INSERT INTO KURSI VALUES ('E1','Teater 5');
INSERT INTO KURSI VALUES ('E2','Teater 5');
INSERT INTO KURSI VALUES ('E3','Teater 5');

SELECT
t.nomor_teater,
k.nomor_kursi
FROM TEATERS t
JOIN KURSI k
ON t.nomor_teater = k.nomor_teater;